exchange:
  rate:
    api:
      url: http://api.exchangeratesapi.io/v1 # URL del API de tasas de cambio
      key: 10124780aa73c83cd1e5b667cf8af774 # Clave de API para autenticación
      logging:
  logstash:
    host: localhost  # o la IP de tu servidor Logstash
    port: 5000       # puerto común para Logstash TCP input